name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.46.0
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Rust
        run: |
          rustup install stable
          rustup default stable
      
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      
      - name: Set up Nextest
        uses: taiki-e/install-action@nextest
      
      - name: Run tests
        run: just test
